/// <reference lib="webworker" />
/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { clientsClaim } from "workbox-core";
import { CacheableResponsePlugin } from "workbox-cacheable-response";
import { ExpirationPlugin } from "workbox-expiration";
import { precacheAndRoute, createHandlerBoundToURL } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { CacheFirst, StaleWhileRevalidate } from "workbox-strategies";

declare const self: ServiceWorkerGlobalScope;

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp("/[^/?]+\\.[^/]+$");
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }: { request: Request; url: URL }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== "navigate") {
      return false;
    }

    // If this is a URL that starts with /_, skip.
    if (url.pathname.startsWith("/_")) {
      return false;
    }

    // If this looks like a URL for a resource, because it contains
    // a file extension, skip.
    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    }

    // Return true to signal that we want to use the handler.
    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + "/index.html")
);

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-origin .png requests like those from in public/
registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) =>
    url.origin === self.location.origin && url.pathname.endsWith(".png"),
  // Customize this strategy as needed, e.g., by changing to CacheFirst.
  new StaleWhileRevalidate({
    cacheName: "images",
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

// Wardrobe photos from Firebase Storage, so outfits still show offline.
// A photo's URL changes when it is replaced, so cache-first never goes stale.
registerRoute(
  ({ url, request }) =>
    url.hostname === "firebasestorage.googleapis.com" &&
    request.destination === "image",
  new CacheFirst({
    cacheName: "wardrobe-photos",
    plugins: [
      // <img> requests are cross-origin without CORS, so responses are opaque (status 0)
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      // Opaque responses count heavily against storage quota: keep the cache bounded
      new ExpirationPlugin({
        maxEntries: 150,
        maxAgeSeconds: 60 * 24 * 60 * 60,
        purgeOnQuotaError: true,
      }),
    ],
  })
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
// A photo shared into Alfred from another app (manifest share_target): keep it
// for the app to pick up, then open the "What are you adding?" chooser
self.addEventListener("fetch", (event) => {
  const url = new URL(event.request.url);
  if (event.request.method !== "POST" || url.pathname !== "/share-target") {
    return;
  }
  event.respondWith(
    (async () => {
      const form = await event.request.formData();
      const photo = form.get("photo");
      if (photo instanceof File) {
        const cache = await caches.open("shared");
        await cache.put(
          "/shared-photo",
          new Response(photo, { headers: { "Content-Type": photo.type } })
        );
      }
      return Response.redirect("/wardrobe?add=1&shared=1", 303);
    })()
  );
});

// The morning reminder, sent as a data-only push by the scheduled function.
// Every push must show a notification (iOS stops delivering otherwise).
self.addEventListener("push", (event) => {
  let payload: { data?: Record<string, string> } & Record<string, string> = {};
  try {
    payload = event.data?.json() ?? {};
  } catch {
    // Not JSON: fall back to a plain reminder
  }
  const data = payload.data ?? payload;
  event.waitUntil(
    self.registration.showNotification(data.title || "Alfred", {
      body: data.body,
      icon: "/icons/icon-192.png",
      tag: "morning-reminder",
      data: { url: data.url || "/", action: data.action },
      // Android shows the button; iOS just opens the app on tap
      ...(data.action && { actions: [{ action: "wear", title: "Wear it" }] }),
    } as NotificationOptions)
  );
});

// Tapping it opens Today, reusing an open Alfred window when there is one
self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  // "Wear it" moves the rotation on; tapping the notification just opens Today
  const { url: openUrl = "/", action } = event.notification.data || {};
  const url = new URL(
    event.action === "wear" && action ? action : openUrl,
    self.location.origin
  ).href;
  event.waitUntil(
    (async () => {
      const windows = await self.clients.matchAll({
        type: "window",
        includeUncontrolled: true,
      });
      const open = windows.find((client) =>
        client.url.startsWith(self.location.origin)
      );
      if (open) {
        await open.focus();
        await open.navigate(url);
      } else {
        await self.clients.openWindow(url);
      }
    })()
  );
});

self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});

// Any other custom service worker logic can go here.
